// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoResizeController from "./auto_resize_controller"
import HelloController from "./hello_controller"
import ScrollToBottomController from "./scroll_to_bottom_controller"
application.register("auto-resize", AutoResizeController)
application.register("hello", HelloController)
application.register("scroll-to-bottom", ScrollToBottomController)
